import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { isLang, DEFAULT_LANG } from "@/lib/i18n";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get("lang")?.value;
  const lang = isLang(cookieLang) ? cookieLang : DEFAULT_LANG;
  const theme = cookieStore.get("theme")?.value;
  const themeAttr = theme === "light" || theme === "dark" ? { "data-theme": theme } : {};

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      {...themeAttr}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
